export { ImpactAnalyzer } from './impact-analyzer.js';
export { PrefetchEngine } from './prefetch-engine.js';
export { DiffEnricher } from './diff-enricher.js';
export { BudgetTracker } from './budget-tracker.js';
export { ConversationMemory } from './conversation-memory.js';
export { SessionLearner } from './session-learner.js';
export { CodeHealthAnalyzer } from './code-health.js';
export { EnrichmentCoordinator } from './enrichment-coordinator.js';
export { ProactiveResponseBuilder, type IntelligenceServices } from './proactive-response.js';
export type { EnrichmentBackend } from './enrichment-backend.js';
export { ClaudeCliBackend } from './backends/claude-cli.js';
export { AnthropicSdkBackend } from './backends/anthropic-sdk.js';
