import { Store } from '@atlasmemory/store';
import fs from 'fs';
import path from 'path';

export type GenerateFormat = 'claude' | 'cursor' | 'copilot' | 'all';

const AUTO_GENERATED_MARKER = '*Auto-generated by [AtlasMemory]';
const AUTO_GENERATED_MARKER_ALT = '*Auto-generated by AtlasMemory';

function isAutoGenerated(filePath: string): boolean {
    if (!fs.existsSync(filePath)) return false;
    const content = fs.readFileSync(filePath, 'utf-8');
    return content.includes(AUTO_GENERATED_MARKER) || content.includes(AUTO_GENERATED_MARKER_ALT);
}

export interface GenerateOptions {
    rootDir: string;
    format?: GenerateFormat;
    output?: string;
    force?: boolean;
}

export interface GenerateResult {
    files: { path: string; content: string }[];
    readiness: AiReadinessScore;
    skipped?: { path: string; reason: string }[];
}

export interface AiReadinessScore {
    overall: number;
    codeCoverage: number;
    descriptionCoverage: number;
    flowCoverage: number;
    evidenceCoverage: number;
    semanticCoverage?: number;
    details: {
        totalFiles: number;
        indexedFiles: number;
        enrichedCards: number;
        totalCards: number;
        flowCount: number;
        anchorCount: number;
        symbolCount: number;
        level3Count?: number;
    };
}

// Noise symbols that appear in every class — not informative
const NOISE_SYMBOLS = new Set(['constructor', 'toString', 'valueOf', 'toJSON']);

// --- Shared data collection ---

interface ProjectData {
    projectName: string;
    projectDesc: string;
    languages: string;
    topDirs: Array<[string, number]>;
    dirSymbols: Map<string, string[]>;
    keyFiles: Array<{ relPath: string; symbolCount: number; purpose: string }>;
    commandLines: string[];
    techStack: string[];
    conventions: string[];
    flowLines: string[];
    readiness: AiReadinessScore;
}

function collectProjectData(store: Store, rootDir: string): ProjectData {
    const files = store.getFiles();
    const pkg = readPackageJson(rootDir);
    const projectName = pkg.name || path.basename(rootDir);
    const projectDesc = pkg.description || '';

    // Paths are already relative in DB
    const projectFiles = files;

    // Languages
    const langCounts = new Map<string, number>();
    for (const file of projectFiles) {
        const ext = path.extname(file.path).toLowerCase();
        const lang = ext === '.ts' || ext === '.tsx' ? 'TypeScript'
            : ext === '.js' || ext === '.jsx' ? 'JavaScript'
            : ext === '.py' ? 'Python' : ext.slice(1);
        if (lang) langCounts.set(lang, (langCounts.get(lang) || 0) + 1);
    }
    const languages = Array.from(langCounts.entries())
        .sort((a, b) => b[1] - a[1])
        .map(([lang, count]) => `${lang} (${count})`)
        .join(', ');

    // Architecture
    const dirCounts = new Map<string, number>();
    const dirSymbols = new Map<string, string[]>();
    for (const file of projectFiles) {
        const rel = file.path.replace(/\\/g, '/');
        const parts = rel.split('/');
        const dir = parts.length > 2 ? parts.slice(0, 2).join('/') : (parts.length > 1 ? parts[0] : '.');
        dirCounts.set(dir, (dirCounts.get(dir) || 0) + 1);

        if (!dirSymbols.has(dir)) dirSymbols.set(dir, []);
        const syms = store.getSymbolsForFile(file.id);
        const existing = dirSymbols.get(dir)!;
        for (const sym of syms) {
            if (sym.visibility === 'public' && !NOISE_SYMBOLS.has(sym.name) && existing.length < 3 && !existing.includes(sym.name)) {
                existing.push(sym.name);
            }
        }
    }
    const topDirs = Array.from(dirCounts.entries())
        .sort((a, b) => b[1] - a[1])
        .slice(0, 12);

    // Key files with smart purposes
    const fileSymbolCounts: Array<{ relPath: string; symbolCount: number; purpose: string }> = [];
    for (const file of projectFiles) {
        const syms = store.getSymbolsForFile(file.id);
        const card = store.getFileCard(file.id);
        const rawPurpose = card?.level1?.purpose || card?.level0?.purpose || '';
        const purpose = rawPurpose.includes('Auto-generated') || rawPurpose.includes('Managed by AtlasMemory')
            ? '' : rawPurpose;
        const relPath = file.path.replace(/\\/g, '/');
        fileSymbolCounts.push({
            relPath,
            symbolCount: syms.length,
            purpose: purpose.length > 80 ? purpose.slice(0, 77) + '...' : purpose,
        });
    }
    const keyFiles = fileSymbolCounts
        .sort((a, b) => {
            // Deprioritize test/example/spec files — source files are more important
            const aIsTest = /\b(tests?|specs?|__tests__|examples?|fixtures?|mocks?|__mocks__)\b/i.test(a.relPath);
            const bIsTest = /\b(tests?|specs?|__tests__|examples?|fixtures?|mocks?|__mocks__)\b/i.test(b.relPath);
            if (aIsTest !== bIsTest) return aIsTest ? 1 : -1;
            return b.symbolCount - a.symbolCount;
        })
        .slice(0, 15);

    // Commands
    const scripts = pkg.scripts || {};
    const importantScripts = ['build', 'test', 'dev', 'start', 'lint', 'format', 'serve', 'deploy',
        'build:all', 'build:bundle', 'eval', 'eval:synth100', 'eval:real'];
    const commandLines: string[] = [];
    for (const key of importantScripts) {
        if (scripts[key]) commandLines.push(`${key.padEnd(20)} # ${scripts[key]}`);
    }
    for (const [key, val] of Object.entries(scripts)) {
        if (!importantScripts.includes(key) && commandLines.length < 20) {
            commandLines.push(`${key.padEnd(20)} # ${val}`);
        }
    }

    // Tech stack
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    const techStack: string[] = [languages];
    const techMap: Record<string, string> = {
        'react': 'React', 'next': 'Next.js', 'express': 'Express',
        'fastify': 'Fastify', 'vue': 'Vue', 'angular': 'Angular', 'svelte': 'Svelte',
        'better-sqlite3': 'SQLite (better-sqlite3)', 'prisma': 'Prisma', 'drizzle-orm': 'Drizzle',
        'tree-sitter': 'Tree-sitter', 'commander': 'Commander.js', 'esbuild': 'esbuild',
        'webpack': 'Webpack', 'vite': 'Vite', 'jest': 'Jest', 'vitest': 'Vitest',
        'mocha': 'Mocha', 'tailwindcss': 'Tailwind CSS', 'eslint': 'ESLint', 'prettier': 'Prettier',
        '@modelcontextprotocol/sdk': 'MCP SDK',
    };
    const seenTech = new Set<string>();
    for (const [dep] of Object.entries(deps)) {
        const baseName = dep.replace(/^@[^/]+\//, '');
        const tech = techMap[dep] || techMap[baseName];
        if (tech && !seenTech.has(tech)) { techStack.push(tech); seenTech.add(tech); }
    }

    // Conventions
    const conventions: string[] = [];
    if (pkg.type === 'module') conventions.push('ESM modules ("type": "module")');
    if (pkg.workspaces) conventions.push('Monorepo (npm workspaces)');
    if (fs.existsSync(path.join(rootDir, 'tsconfig.json'))) conventions.push('TypeScript with tsconfig.json');
    if (fs.existsSync(path.join(rootDir, '.eslintrc.js')) || fs.existsSync(path.join(rootDir, '.eslintrc.json')) || fs.existsSync(path.join(rootDir, 'eslint.config.js'))) conventions.push('ESLint configured');
    if (fs.existsSync(path.join(rootDir, '.prettierrc')) || fs.existsSync(path.join(rootDir, '.prettierrc.json'))) conventions.push('Prettier configured');
    if (fs.existsSync(path.join(rootDir, 'Dockerfile'))) conventions.push('Docker containerized');
    if (fs.existsSync(path.join(rootDir, '.github/workflows'))) conventions.push('GitHub Actions CI/CD');
    if (fs.existsSync(path.join(rootDir, '.atlas'))) conventions.push('AtlasMemory indexed (.atlas/atlas.db)');

    // Flows — prefer cross-file, skip self-recursive
    const allFlows = store.getAllFlowCards();
    const meaningfulFlows = allFlows
        .filter(f => {
            const parts = f.summary.split(' -> ');
            // Skip self-recursive (A -> A)
            if (parts.length === 2 && parts[0] === parts[1]) return false;
            // Prefer 2-hop cross-file
            return true;
        })
        .sort((a, b) => b.hopCount - a.hopCount)
        .slice(0, 8);
    const flowLines = meaningfulFlows.map(f => `${f.summary} (${f.hopCount}-hop)`);

    const readiness = computeAiReadiness(store);

    return { projectName, projectDesc, languages, topDirs, dirSymbols, keyFiles, commandLines, techStack, conventions, flowLines, readiness };
}

function readPackageJson(rootDir: string): any {
    try { return JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf-8')); } catch { return {}; }
}

// --- Format renderers ---

export function generateClaudeMd(store: Store, options: GenerateOptions): string {
    const data = collectProjectData(store, options.rootDir);
    return renderClaudeMd(data);
}

function renderClaudeMd(d: ProjectData): string {
    const s: string[] = [];

    s.push(`# ${d.projectName}`);
    if (d.projectDesc) s.push(`\n${d.projectDesc}`);

    s.push('\n## Architecture');
    s.push('```');
    for (const [dir, count] of d.topDirs) {
        const syms = d.dirSymbols.get(dir) || [];
        const symStr = syms.length > 0 ? ` → ${syms.join(', ')}` : '';
        s.push(`${dir.padEnd(30)} ${String(count).padStart(3)} files${symStr}`);
    }
    s.push('```');

    s.push('\n## Key Files');
    for (const kf of d.keyFiles) {
        const purposeStr = kf.purpose ? ` — ${kf.purpose}` : '';
        s.push(`- **\`${kf.relPath}\`**${purposeStr}`);
    }

    if (d.commandLines.length > 0) {
        s.push('\n## Commands');
        s.push('```bash');
        for (const line of d.commandLines) s.push(line);
        s.push('```');
    }

    if (d.techStack.length > 0) {
        s.push('\n## Tech Stack');
        s.push(d.techStack.join(', '));
    }

    if (d.conventions.length > 0) {
        s.push('\n## Conventions');
        for (const conv of d.conventions) s.push(`- ${conv}`);
    }

    if (d.flowLines.length > 0) {
        s.push('\n## Key Data Flows');
        for (const fl of d.flowLines) s.push(`- ${fl}`);
    }

    s.push('\n## AI Readiness Score');
    s.push(`**${d.readiness.overall}/100**\n`);
    s.push('| Metric | Score | Details |');
    s.push('|--------|-------|---------|');
    s.push(`| Code Coverage | ${d.readiness.codeCoverage}% | ${d.readiness.details.indexedFiles}/${d.readiness.details.totalFiles} files indexed |`);
    s.push(`| Description Quality | ${d.readiness.descriptionCoverage}% | ${d.readiness.details.enrichedCards}/${d.readiness.details.totalCards} cards enriched |`);
    s.push(`| Flow Analysis | ${d.readiness.flowCoverage}% | ${d.readiness.details.flowCount} call flows traced |`);
    s.push(`| Evidence Anchors | ${d.readiness.evidenceCoverage}% | ${d.readiness.details.anchorCount} anchors linked |`);
    if (d.readiness.semanticCoverage !== undefined) {
        s.push(`| Semantic Coverage | ${d.readiness.semanticCoverage}% | ${d.readiness.details.level3Count || 0}/${d.readiness.details.totalFiles} files with AI intent cards |`);
    }

    s.push('\n---');
    s.push('*Auto-generated by [AtlasMemory](https://github.com/Bpolat0/atlasmemory). Re-run `atlasmemory generate` to update.*');

    return s.join('\n');
}

function renderCursorRules(d: ProjectData): string {
    const s: string[] = [];

    s.push(`# ${d.projectName} — Cursor Rules`);
    if (d.projectDesc) s.push(`\n${d.projectDesc}`);

    s.push('\n## Project Structure');
    for (const [dir, count] of d.topDirs) {
        const syms = d.dirSymbols.get(dir) || [];
        const symStr = syms.length > 0 ? `: ${syms.join(', ')}` : '';
        s.push(`- \`${dir}/\` (${count} files)${symStr}`);
    }

    s.push('\n## Important Files');
    for (const kf of d.keyFiles.slice(0, 10)) {
        const purposeStr = kf.purpose ? ` — ${kf.purpose}` : '';
        s.push(`- \`${kf.relPath}\`${purposeStr}`);
    }

    if (d.techStack.length > 0) {
        s.push(`\n## Tech Stack\n${d.techStack.join(', ')}`);
    }

    if (d.conventions.length > 0) {
        s.push('\n## Conventions');
        for (const conv of d.conventions) s.push(`- ${conv}`);
    }

    if (d.commandLines.length > 0) {
        s.push('\n## Commands');
        for (const line of d.commandLines.slice(0, 8)) {
            const [cmd, ...rest] = line.split('#');
            s.push(`- \`${cmd.trim()}\` —${rest.join('#')}`);
        }
    }

    if (d.flowLines.length > 0) {
        s.push('\n## Key Flows');
        for (const fl of d.flowLines.slice(0, 5)) s.push(`- ${fl}`);
    }

    s.push('\n---');
    s.push('*Auto-generated by AtlasMemory. Re-run `atlasmemory generate --format cursor` to update.*');

    return s.join('\n');
}

function renderCopilotInstructions(d: ProjectData): string {
    const s: string[] = [];

    s.push(`# ${d.projectName}`);
    if (d.projectDesc) s.push(`\n${d.projectDesc}`);

    s.push('\n## Architecture Overview');
    for (const [dir, count] of d.topDirs) {
        const syms = d.dirSymbols.get(dir) || [];
        const symStr = syms.length > 0 ? ` — key exports: ${syms.join(', ')}` : '';
        s.push(`- \`${dir}/\` contains ${count} files${symStr}`);
    }

    s.push('\n## Key Files to Reference');
    for (const kf of d.keyFiles.slice(0, 10)) {
        const purposeStr = kf.purpose ? `: ${kf.purpose}` : '';
        s.push(`- \`${kf.relPath}\`${purposeStr}`);
    }

    if (d.techStack.length > 0) {
        s.push(`\n## Technology\n${d.techStack.join(', ')}`);
    }

    if (d.conventions.length > 0) {
        s.push('\n## Project Conventions');
        for (const conv of d.conventions) s.push(`- ${conv}`);
    }

    if (d.commandLines.length > 0) {
        s.push('\n## Build & Test Commands');
        s.push('```bash');
        for (const line of d.commandLines.slice(0, 8)) s.push(line);
        s.push('```');
    }

    s.push('\n---');
    s.push('*Auto-generated by AtlasMemory. Re-run `atlasmemory generate --format copilot` to update.*');

    return s.join('\n');
}

// --- Public API ---

export function generateAll(store: Store, options: GenerateOptions): GenerateResult {
    const data = collectProjectData(store, options.rootDir);
    const format = options.format || 'claude';
    const results: GenerateResult = { files: [], readiness: data.readiness };

    if (format === 'claude' || format === 'all') {
        const targetPath = path.join(options.rootDir, 'CLAUDE.md');
        if (!options.force && fs.existsSync(targetPath) && !isAutoGenerated(targetPath)) {
            results.skipped = results.skipped || [];
            results.skipped.push({ path: targetPath, reason: 'Hand-written file detected. Use --force to overwrite.' });
        } else {
            results.files.push({
                path: targetPath,
                content: renderClaudeMd(data),
            });
        }
    }

    if (format === 'cursor' || format === 'all') {
        const targetPath = path.join(options.rootDir, '.cursorrules');
        if (!options.force && fs.existsSync(targetPath) && !isAutoGenerated(targetPath)) {
            results.skipped = results.skipped || [];
            results.skipped.push({ path: targetPath, reason: 'Hand-written file detected. Use --force to overwrite.' });
        } else {
            results.files.push({
                path: targetPath,
                content: renderCursorRules(data),
            });
        }
    }

    if (format === 'copilot' || format === 'all') {
        const ghDir = path.join(options.rootDir, '.github');
        const targetPath = path.join(ghDir, 'copilot-instructions.md');
        if (!options.force && fs.existsSync(targetPath) && !isAutoGenerated(targetPath)) {
            results.skipped = results.skipped || [];
            results.skipped.push({ path: targetPath, reason: 'Hand-written file detected. Use --force to overwrite.' });
        } else {
            results.files.push({
                path: targetPath,
                content: renderCopilotInstructions(data),
            });
        }
    }

    return results;
}

export function computeAiReadiness(store: Store): AiReadinessScore {
    const files = store.getFiles();
    const totalFiles = files.length;

    const totalCards = (store.db.prepare('SELECT COUNT(*) as n FROM file_cards').get() as { n: number }).n;
    // A card is "described" if it has: (a) level1 without the placeholder note, OR (b) level3 (deterministic/semantic enrichment)
    const awaitingCount = (store.db.prepare(
        "SELECT COUNT(*) as n FROM file_cards WHERE card_level1 LIKE '%Awaiting AI enrichment%' AND (card_level3 IS NULL OR card_level3 = 'null')"
    ).get() as { n: number }).n;
    const enrichedCards = totalCards - awaitingCount;

    const flowCount = (store.db.prepare('SELECT COUNT(*) as n FROM flow_cards').get() as { n: number }).n;
    const anchorCount = (store.db.prepare('SELECT COUNT(*) as n FROM anchors').get() as { n: number }).n;
    const symbolCount = (store.db.prepare('SELECT COUNT(*) as n FROM symbols').get() as { n: number }).n;

    const codeCoverage = totalFiles > 0 ? 100 : 0;
    const descriptionCoverage = totalCards > 0 ? Math.round((enrichedCards / totalCards) * 100) : 0;

    const filesWithFlows = new Set(
        (store.db.prepare('SELECT DISTINCT file_id FROM flow_cards').all() as { file_id: string }[]).map(r => r.file_id)
    ).size;
    const flowCoverage = totalFiles > 0 ? Math.min(100, Math.round((filesWithFlows / totalFiles) * 100)) : 0;

    const symbolsWithAnchors = (store.db.prepare(
        'SELECT COUNT(DISTINCT s.id) as n FROM symbols s INNER JOIN anchors a ON s.file_id = a.file_id AND s.start_line = a.start_line AND s.end_line = a.end_line'
    ).get() as { n: number }).n;
    const evidenceCoverage = symbolCount > 0 ? Math.round((symbolsWithAnchors / symbolCount) * 100) : 0;

    // Phase 20: Conditional Semantic Coverage metric (only when Level3 cards exist)
    let level3Count = 0;
    try {
        level3Count = (store.db.prepare(
            "SELECT COUNT(*) as n FROM file_cards WHERE card_level3 IS NOT NULL"
        ).get() as { n: number }).n;
    } catch (e) { /* card_level3 column may not exist in older DBs */ }

    const hasLevel3 = level3Count > 0;
    const semanticCoverage = hasLevel3 && totalFiles > 0 ? Math.round((level3Count / totalFiles) * 100) : undefined;

    // Reweight when Level3 cards exist: Code 22%, Desc 25%, Flow 18%, Evidence 20%, Semantic 15%
    const overall = hasLevel3
        ? Math.round(codeCoverage * 0.22 + descriptionCoverage * 0.25 + flowCoverage * 0.18 + evidenceCoverage * 0.20 + (semanticCoverage || 0) * 0.15)
        : Math.round(codeCoverage * 0.25 + descriptionCoverage * 0.30 + flowCoverage * 0.20 + evidenceCoverage * 0.25);

    return {
        overall, codeCoverage, descriptionCoverage, flowCoverage, evidenceCoverage,
        ...(semanticCoverage !== undefined ? { semanticCoverage } : {}),
        details: { totalFiles, indexedFiles: totalFiles, enrichedCards, totalCards, flowCount, anchorCount, symbolCount, ...(hasLevel3 ? { level3Count } : {}) }
    };
}

export function renderReadinessBar(score: number): string {
    const filled = Math.round(score / 5);
    const empty = 20 - filled;
    const bar = '\u2588'.repeat(filled) + '\u2591'.repeat(empty);
    const label = score >= 80 ? 'EXCELLENT' : score >= 60 ? 'GOOD' : score >= 40 ? 'FAIR' : 'NEEDS WORK';
    return `${bar} ${score}/100 ${label}`;
}
