import type { FileCard, SymbolCard, CodeSymbol } from '@atlasmemory/core';
import crypto from 'crypto';
import nodePath from 'path';

import { LLMService } from './llm.js';

export class CardGenerator {
    private llm?: LLMService;

    constructor(llm?: LLMService) {
        this.llm = llm;
    }

    async generateFileCard(
        fileId: string,
        path: string,
        symbols: CodeSymbol[],
        content?: string,
        anchors: import('@atlasmemory/core').Anchor[] = [],
        flowCards: import('@atlasmemory/core').FlowCard[] = []
    ): Promise<FileCard> {
        const exports = symbols.filter(s => s.visibility === 'public').map(s => s.name);

        // Deterministic Level 0
        const level0 = {
            purpose: 'Managed by AtlasMemory',
            exports,
            sideEffects: []
        };

        let level1: FileCard['level1'] | undefined;

        // Cost Control: Mini-cards for simple files
        let useLLM = !!(this.llm && content);
        if (useLLM) {
            const lowerPath = path.toLowerCase();
            const filename = nodePath.basename(lowerPath);

            // 1. Definition files
            if (lowerPath.endsWith('.d.ts')) useLLM = false;

            // 2. Types/Constants/Barrels
            if (filename === 'types.ts' || filename === 'constants.ts' || filename === 'index.ts') {
                // For index.ts, only skip if small (likely just exports)
                if (filename === 'index.ts' && content!.split('\n').length < 50) useLLM = false;
                else if (filename !== 'index.ts') useLLM = false;
            }
        }

        if (useLLM && content) {
            // Prepare anchor candidates with signatures for LLM
            // We assume anchors aligned with symbols or we just match them
            // For now, let's just map symbols to their anchors if possible. 
            // In Indexer, we pushed anchor then symbol, so they might align. 
            // Better to just pass all anchors and try to find a symbol name for them.

            const candidates = anchors.map(a => {
                const sym = symbols.find(s => s.startLine === a.startLine && s.endLine === a.endLine);
                return {
                    id: a.id,
                    signature: sym ? sym.signature : 'Unknown Block',
                    startLine: a.startLine,
                    endLine: a.endLine
                };
            });

            const jsonString = await this.llm!.summarizeFile(path, content, symbols.map(s => s.name), candidates);
            try {
                const data = JSON.parse(jsonString);

                // Resolve selected IDs to Anchor objects (Validation mainly)
                const selectedAnchorIds: string[] = [];
                if (data.evidenceAnchorIds && Array.isArray(data.evidenceAnchorIds)) {
                    // Validate existence? Or trust LLM?
                    // We should trust but verify if we enforce strict candidates.
                    for (const id of data.evidenceAnchorIds) {
                        const match = anchors.find(a => a.id === id);
                        if (match) selectedAnchorIds.push(match.id);
                    }
                }

                level1 = {
                    purpose: data.purpose || 'No purpose provided',
                    publicApi: data.publicApi || [],
                    sideEffects: data.sideEffects || [],
                    dependencies: data.dependencies || [],
                    notes: data.notes || 'Generated by LLM',
                    evidenceAnchorIds: selectedAnchorIds
                };
            } catch (e) {
                console.error('Failed to parse LLM JSON:', e);
                level1 = {
                    purpose: 'Failed to parse summary',
                    publicApi: [],
                    sideEffects: [],
                    dependencies: [],
                    notes: 'JSON Parse Error',
                    evidenceAnchorIds: []
                };
            }
        } else {
            // Deterministic Fallback with smart purpose generation
            const publicSymbols = symbols.filter(s => s.visibility === 'public');
            const selectedAnchors = anchors.filter(a =>
                publicSymbols.some(s => s.startLine === a.startLine && s.endLine === a.endLine)
            );
            if (selectedAnchors.length === 0 && anchors.length > 0) {
                const sorted = [...anchors].sort((a, b) => (b.endLine - b.startLine) - (a.endLine - a.startLine));
                selectedAnchors.push(...sorted.slice(0, 3));
            }

            const purpose = this.generateSmartPurpose(path, symbols, exports);

            level1 = {
                purpose,
                publicApi: exports,
                sideEffects: [],
                dependencies: [],
                notes: 'Awaiting AI enrichment',
                evidenceAnchorIds: selectedAnchors.map(a => a.id)
            };
        }

        const level2 = this.generateLevel2(content || '', symbols, anchors, flowCards);

        const cardHash = crypto.createHash('sha256')
            .update(JSON.stringify(level0) + (level1 ? JSON.stringify(level1) : '') + JSON.stringify(level2))
            .digest('hex');

        return {
            fileId,
            path,
            level0,
            level1,
            level2,
            cardHash
        };
    }

    private generateLevel2(
        content: string,
        symbols: CodeSymbol[],
        anchors: import('@atlasmemory/core').Anchor[],
        flowCards: import('@atlasmemory/core').FlowCard[]
    ): import('@atlasmemory/core').Level2FileCard {
        const byRange = new Map<string, string>();
        for (const anchor of anchors) {
            byRange.set(`${anchor.startLine}:${anchor.endLine}`, anchor.id);
        }

        const flows = flowCards
            .filter(flow => flow.evidenceAnchorIds.length > 0)
            .slice(0, 4)
            .map(flow => ({
                text: flow.summary,
                evidenceAnchorIds: flow.evidenceAnchorIds
            }));

        const invariants: import('@atlasmemory/core').EvidenceClaim[] = [];
        const publicSymbols = symbols.filter(s => s.visibility === 'public').slice(0, 6);
        for (const symbol of publicSymbols) {
            const anchorId = byRange.get(`${symbol.startLine}:${symbol.endLine}`);
            if (!anchorId) continue;
            invariants.push({
                text: `Contract: ${symbol.signature}`,
                evidenceAnchorIds: [anchorId]
            });
        }

        const envDependencies = this.extractEnvDependencies(content, anchors);

        return {
            flows,
            invariants,
            envDependencies
        };
    }

    private extractEnvDependencies(
        content: string,
        anchors: import('@atlasmemory/core').Anchor[]
    ): import('@atlasmemory/core').EnvDependencyClaim[] {
        if (!content) return [];

        const lines = content.split(/\r?\n/);
        const envMap = new Map<string, import('@atlasmemory/core').EnvDependencyClaim>();

        const addDependency = (name: string, source: 'process.env' | 'os.environ', lineNumber: number) => {
            const anchor = anchors.find(a => a.startLine <= lineNumber && a.endLine >= lineNumber);
            if (!anchor) return;

            const key = `${source}:${name}`;
            const existing = envMap.get(key);
            if (existing) {
                if (!existing.evidenceAnchorIds.includes(anchor.id)) {
                    existing.evidenceAnchorIds.push(anchor.id);
                }
                return;
            }

            envMap.set(key, {
                name,
                source,
                evidenceAnchorIds: [anchor.id]
            });
        };

        for (let i = 0; i < lines.length; i++) {
            const line = lines[i];
            const processDotRegex = /process\.env\.([A-Z0-9_]+)/g;
            const processBracketRegex = /process\.env\[['\"]([A-Z0-9_]+)['\"]\]/g;
            const pythonRegex = /os\.environ(?:\.get)?\(['\"]([A-Z0-9_]+)['\"]\)/g;

            let match: RegExpExecArray | null;
            while ((match = processDotRegex.exec(line)) !== null) {
                addDependency(match[1], 'process.env', i + 1);
            }
            while ((match = processBracketRegex.exec(line)) !== null) {
                addDependency(match[1], 'process.env', i + 1);
            }
            while ((match = pythonRegex.exec(line)) !== null) {
                addDependency(match[1], 'os.environ', i + 1);
            }
        }

        return Array.from(envMap.values());
    }

    private generateSmartPurpose(filePath: string, symbols: CodeSymbol[], exports: string[]): string {
        const basename = nodePath.basename(filePath).replace(/\.[^.]+$/, '');
        const dirName = nodePath.basename(nodePath.dirname(filePath));

        // Humanize file name: "card-generator" → "Card generator", "authService" → "Auth service"
        const humanName = basename
            .replace(/[-_]/g, ' ')
            .replace(/([a-z])([A-Z])/g, '$1 $2')
            .toLowerCase()
            .replace(/^\w/, c => c.toUpperCase());

        // Count symbols by kind
        const kindCounts = new Map<string, number>();
        for (const sym of symbols) {
            kindCounts.set(sym.kind, (kindCounts.get(sym.kind) || 0) + 1);
        }

        // Build kind summary: "2 functions, 1 class"
        const kindParts: string[] = [];
        const kindOrder: Array<[string, string]> = [['class', 'class'], ['function', 'function'], ['method', 'method'], ['type', 'type'], ['const', 'constant']];
        for (const [kind, label] of kindOrder) {
            const count = kindCounts.get(kind);
            if (count) kindParts.push(`${count} ${label}${count > 1 ? (label.endsWith('s') ? 'es' : 's') : ''}`);
        }

        // Build purpose
        const topExports = exports.slice(0, 3).join(', ');
        const moreCount = exports.length > 3 ? ` +${exports.length - 3} more` : '';
        const kindSummary = kindParts.length > 0 ? ` (${kindParts.join(', ')})` : '';

        if (exports.length > 0) {
            return `${humanName}: exports ${topExports}${moreCount}${kindSummary}`;
        }

        if (symbols.length > 0) {
            const topSymbols = symbols.slice(0, 3).map(s => s.name).join(', ');
            return `${humanName}: defines ${topSymbols}${kindSummary}`;
        }

        // Minimal fallback
        return `${humanName} module (${dirName})`;
    }

    generateSymbolCard(symbol: CodeSymbol): SymbolCard {
        return {
            symbolId: symbol.id,
            level0: {
                signature: symbol.signature,
                summary: `Symbol: ${symbol.name} (${symbol.kind})`
            }
        };
    }
}
